export const VALID_CATEGORIES = [
  "business",
  "crime",
  "domestic",
  "education",
  "entertainment",
  "environment",
  "food",
  "health",
  "lifestyle",
  "politics",
  "science",
  "sports",
  "technology",
  "top",
  "tourism",
  "world",
  "other",
];
export const LANGUAGE_CODES = {
  Afrikaans: "af",
  Albanian: "sq",
  Amharic: "am",
  Arabic: "ar",
  Armenian: "hy",
  Assamese: "as",
  Azerbaijani: "az",
  Bambara: "bm",
  Basque: "eu",
  Belarusian: "be",
  Bengali: "bn",
  Bosnian: "bs",
  Bulgarian: "bg",
  Burmese: "my",
  Catalan: "ca",
  "Central Kurdish": "ckb",
  Chinese: "zh",
  Croatian: "hr",
  Czech: "cs",
  Danish: "da",
  Dutch: "nl",
  English: "en",
  Estonian: "et",
  Filipino: "pi",
  Finnish: "fi",
  French: "fr",
  Galician: "gl",
  Georgian: "ka",
  German: "de",
  Greek: "el",
  Gujarati: "gu",
  Hausa: "ha",
  Hebrew: "he",
  Hindi: "hi",
  Hungarian: "hu",
  Icelandic: "is",
  Indonesian: "id",
  Italian: "it",
  Japanese: "jp",
  Kannada: "kn",
  Kazakh: "kz",
  Khmer: "kh",
  Kinyarwanda: "rw",
  Korean: "ko",
  Kurdish: "ku",
  Latvian: "lv",
  Lithuanian: "lt",
  Luxembourgish: "lb",
  Macedonian: "mk",
  Malay: "ms",
  Malayalam: "ml",
  Maltese: "mt",
  Maori: "mi",
  Marathi: "mr",
  Mongolian: "mn",
  Nepali: "ne",
  Norwegian: "no",
  Oriya: "or",
  Pashto: "ps",
  Persian: "fa",
  Polish: "pl",
  Portuguese: "pt",
  Punjabi: "pa",
  Romanian: "ro",
  Russian: "ru",
  Samoan: "sm",
  Serbian: "sr",
  Shona: "sn",
  Sindhi: "sd",
  Sinhala: "si",
  Slovak: "sk",
  Slovenian: "sl",
  Somali: "so",
  Spanish: "es",
  Swahili: "sw",
  Swedish: "sv",
  Tajik: "tg",
  Tamil: "ta",
  Telugu: "te",
  Thai: "th",
  "Traditional Chinese": "zht",
  Turkish: "tr",
  Turkmen: "tk",
  Ukrainian: "uk",
  Urdu: "ur",
  Uzbek: "uz",
  Vietnamese: "vi",
  Welsh: "cy",
  Zulu: "zu",
};
export const COUNTRY_CODES = {
  "AFGHANISTAN": "af",
  "ALBANIA": "al",
  "ALGERIA": "dz",
  "AMERICAN SAMOA": "as",
  "ANDORRA": "ad",
  "ANGOLA": "ao",
  "ANGUILLA": "ai",
  "ANTARCTICA": "aq",
  "ANTIGUA AND BARBUDA": "ag",
  "ARGENTINA": "ar",
  "ARMENIA": "am",
  "ARUBA": "aw",
  "AUSTRALIA": "au",
  "AUSTRIA": "at",
  "AZERBAIJAN": "az",
  "BAHAMAS": "bs",
  "BAHRAIN": "bh",
  "BANGLADESH": "bd",
  "BARBADOS": "bb",
  "BELARUS": "by",
  "BELGIUM": "be",
  "BELIZE": "bz",
  "BENIN": "bj",
  "BERMUDA": "bm",
  "BHUTAN": "bt",
  "BOLIVIA": "bo",
  "BOSNIA AND HERZEGOVINA": "ba",
  "BOTSWANA": "bw",
  "BOUVET ISLAND": "bv",
  "BRAZIL": "br",
  "BRITISH INDIAN OCEAN TERRITORY": "io",
  "BRUNEI": "bn",
  "BRUNEI DARUSSALAM": "bn",
  "BULGARIA": "bg",
  "BURKINA FASCO": "bf",
  "BURUNDI": "bi",
  "CAMBODIA": "kh",
  "CAMEROON": "cm",
  "CANADA": "ca",
  "CAPE VERDE": "cv",
  "CAYMAN ISLANDS": "ky",
  "CENTRAL AFRICAN REPUBLIC": "cf",
  "CHAD": "td",
  "CHILE": "cl",
  "CHINA": "cn",
  "CHRISTMAS ISLAND": "cx",
  "COLOMBIA": "co",
  "COMOROS": "km",
  "CONGO": "cg",
  "CONGO, THE DEMOCRATIC REPUBLIC OF THE": "cd",
  "DR CONGO": "cd",
  "COOK ISLANDS": "ck",
  "COSTA RICA": "cr",
  "COTE D IVOIRE": "ci",
  "IVORY COAST": "ci",
  "CROATIA": "hr",
  "CUBA": "cu",
  "CYPRUS": "cy",
  "CURAÇAO": "cw",
  "CZECH REPUBLIC": "cz",
  "DENMARK": "dk",
  "DJIBOUTI": "dj",
  "DOMINICA": "dm",
  "DOMINICAN REPUBLIC": "do",
  "EAST TIMOR": "tp",
  "ECUADOR": "ec",
  "EGYPT": "eg",
  "EL SALVADOR": "sv",
  "EQUATORIAL GUINEA": "gq",
  "ERITREA": "er",
  "ESTONIA": "ee",
  "ETHIOPIA": "et",
  "FALK": "fk",
  "FAROE ISLANDS": "fo",
  "FIJI": "fj",
  "FINLAND": "fi",
  "FRANCE": "fr",
  "FRENCH GUIANA": "gf",
  "FRENCH POLYNESIA": "pf",
  "FRENCH SOUTHERN TERRITORIES": "tf",
  "GABON": "ga",
  "GAMBIA": "gm",
  "GEORGIA": "ge",
  "GERMANY": "de",
  "GHANA": "gh",
  "GIBRALTAR": "gi",
  "GREECE": "gr",
  "GREENLAND": "gl",
  "GRENADA": "gd",
  "GUADELOUPE": "gp",
  "GUAM": "gu",
  "GUATEMALA": "gt",
  "GUINEA": "gn",
  "GUINEA-BISSAU": "gw",
  "GUYANA": "gy",
  "HAITI": "ht",
  "HEARD ISLAND AND MCDONALD ISLANDS": "hm",
  "HOLY": "va",
  "VATICAN": "va",
  "HONDURAS": "hn",
  "HONG KONG": "hk",
  "HUNGARY": "hu",
  "ICELAND": "is",
  "INDIA": "in",
  "INDONESIA": "id",
  "IRAN": "ir",
  "IRAN, ISLAMIC REPUBLIC OF": "ir",
  "IRAQ": "iq",
  "IRELAND": "ie",
  "ISRAEL": "il",
  "ITALY": "it",
  "JAMAICA": "jm",
  "JAPAN": "jp",
  "JERSEY": "je",
  "JORDAN": "jo",
  "KAZAKHSTAN": "kz",
  "KENYA": "ke",
  "KIRIBATI": "ki",
  "KOSOVO": "xk",
  "KOREA DEMOCRATIC PEOPLES REPUBLIC OF": "kp",
  "NORTH KOREA": "kp",
  "KOREA REPUBLIC OF": "kr",
  "SOUTH KOREA": "kr",
  "KUWAIT": "kw",
  "KYRGYZSTAN": "kg",
  "LAOS": "la",
  "LAO PEOPLES DEMOCRATIC REPUBLIC": "la",
  "LATVIA": "lv",
  "LEBANON": "lb",
  "LESOTHO": "ls",
  "LIBERIA": "lr",
  "LIBYA": "ly",
  "LIBYAN ARAB JAMAHIRIYA": "ly",
  "LIECHTENSTEIN": "li",
  "LITHUANIA": "lt",
  "LUXEMBOURG": "lu",
  "MACAU": "mo",
  "MACEDONIA": "mk",
  "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF": "mk",
  "MADAGASCAR": "mg",
  "MALAWI": "mw",
  "MALAYSIA": "my",
  "MALDIVES": "mv",
  "MALI": "ml",
  "MALTA": "mt",
  "MARSHALL ISLANDS": "mh",
  "MARTINIQUE": "mq",
  "MAURITANIA": "mr",
  "MAURITIUS": "mu",
  "MAYOTTE": "yt",
  "MEXICO": "mx",
  "MICRONESIA": "fm",
  "MICRONESIA, FEDERATED STATES OF": "fm",
  "MOLDOVA": "md",
  "MOLDOVA, REPUBLIC OF": "md",
  "MONACO": "mc",
  "MONGOLIA": "mn",
  "MONTENEGRO": "me",
  "MONTSERRAT": "ms",
  "MOROCCO": "ma",
  "MOZAMBIQUE": "mz",
  "MYANMAR": "mm",
  "NAMIBIA": "na",
  "NAURU": "nr",
  "NEPAL": "np",
  "NETHERLAND": "nl",
  "NETHERLANDS ANTILLES": "an",
  "NEW CALEDONIA": "nc",
  "NEW ZEALAND": "nz",
  "NICARAGUA": "ni",
  "NIGER": "ne",
  "NIGERIA": "ng",
  "NIUE": "nu",
  "NORFOLK ISLAND": "nf",
  "NORTHERN MARIANA ISLANDS": "mp",
  "NORWAY": "no",
  "OMAN": "om",
  "PAKISTAN": "pk",
  "PALAU": "pw",
  "PALESTINE": "ps",
  "PALESTINIAN TERRITORY, OCCUPIED": "ps",
  "PANAMA": "pa",
  "PAPUA NEW GUINEA": "pg",
  "PARAGUAY": "py",
  "PERU": "pe",
  "PHILIPPINES": "ph",
  "PITCAIRN": "pn",
  "POLAND": "pl",
  "PORTUGAL": "pt",
  "PUERTO RICO": "pr",
  "QATAR": "qa",
  "REUNION": "re",
  "ROMANIA": "ro",
  "RUSSIA": "ru",
  "RUSSIAN FEDERATION": "ru",
  "RWANDA": "rw",
  "SAINT HELENA": "sh",
  "SAINT KITTS AND NEVIS": "kn",
  "SAINT LUCIA": "lc",
  "SAINT MARTIN(DUTCH)": "sx",
  "SAINT PIERRE AND MIQUELON": "pm",
  "SAINT VINCENT AND THE GRENADINES": "vc",
  "SAMOA": "ws",
  "SAN MARINO": "sm",
  "SAO TOME AND PRINCIPE": "st",
  "SAUDI ARABIA": "sa",
  "SENEGAL": "sn",
  "SERBIA": "rs",
  "SEYCHELLES": "sc",
  "SIERRA LEONE": "sl",
  "SINGAPORE": "sg",
  "SLOVAKIA": "sk",
  "SLOVENIA": "si",
  "SOLOMON ISLANDS": "sb",
  "SOMALIA": "so",
  "SOUTH AFRICA": "za",
  "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS": "gs",
  "SPAIN": "es",
  "SRI LANKA": "lk",
  "SUDAN": "sd",
  "SURINAME": "sr",
  "SVALBARD AND JAN MAYEN": "sj",
  "SWAZILAND": "sz",
  "ESWATINI": "sz",
  "SWEDEN": "se",
  "SWITZERLAND": "ch",
  "SYRIA": "sy",
  "SYRIAN ARAB REPUBLIC": "sy",
  "TAIWAN": "tw",
  "TAIWAN, PROVINCE OF CHINA": "tw",
  "TAJIKISTAN": "tj",
  "TANZANIA": "tz",
  "TANZANIA, UNITED REPUBLIC OF": "tz",
  "THAILAND": "th",
  "TOGO": "tg",
  "TOKELAU": "tk",
  "TONGA": "to",
  "TRINIDAD AND TOBAGO": "tt",
  "TUNISIA": "tn",
  "TURKEY": "tr",
  "TURKMENISTAN": "tm",
  "TURKS AND CAICOS ISLANDS": "tc",
  "TUVALU": "tv",
  "UGANDA": "ug",
  "UKRAINE": "ua",
  "UNITED ARAB EMIRATES": "ae",
  "UNITED KINGDOM": "gb",
  "UNITED STATES": "us",
  "UNITED STATES OF AMERICA": "us",
  "URUGUAY": "uy",
  "UZBEKISTAN": "uz",
  "VANUATU": "vu",
  "VATICAN": "va",
  "VENEZUELA": "ve",
  "VIETNAM": "vn",
  "VIRGIN ISLANDS (BRITISH)": "vg",
  "VIRGIN ISLANDS, BRITISH": "vg",
  "VIRGIN ISLANDS, U.S.": "vi",
  "WALLIS AND FUTUNA": "wf",
  "WESTERN SAHARA": "eh",
  "WORLD": "wo",
  "YEMEN": "ye",
  "YUGOSLAVIA": "yu",
  "ZAMBIA": "zm",
  "ZIMBABWE": "zw"
};


